version: '3.4'

services:
  productdb:
    image: postgres
  discountdb:
    image: postgres
  basketdb:
    image: redis:alpine
  pgadmin:
   image: dpage/pgadmin4
  products.api:
    image: ${DOCKER_REGISTRY-}productsapi
    build:
      context: .
      dockerfile: src/services/products/products.Api/Dockerfile
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: src/services/Baskets/Basket.Api/Dockerfile
volumes:
  postgres_data:
  pgadmin_data: